ADD: fetch eth data and store
Conflux-Chain/neurahive-scan pull request #3
Opened 2023-09-04 03:21 UTC by Argeric

fetch eth data from evm space block by block, and persist into db

2023-09-04 06:04 UTC, Tigo9527 commented on store/eth_data.go
> +			if blockReceipts == nil {
Better to check it before `for` loop

2023-09-04 06:09 UTC, Tigo9527 approved these changes
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @boqiu and @wanliqun)



<!-- Sent from Reviewable.io -->

2023-09-04 06:47 UTC, boqiu requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3)* status: all files reviewed, 14 unresolved discussions (waiting on @Argeric and @wanliqun)

___
*[`store/eth_data.go` line 22 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdTpzCLE4vqAjR6K9_1:-NdTpzCMEC9cfbCjCiNF:b-fx61x1) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5013ad0a6eb2ce17e3d74a8bfb3d5f9652572a4/store/eth_data.go#L22)):*
> ```Go
> func QueryEthData(w3c *web3go.Client, blockNumber uint64, useBatch bool) (*EthData, error) {
> 	// get block
> 	block, err := w3c.Eth.BlockByNumber(types.BlockNumber(blockNumber), true)
> ```

Is it necessary to return all transactions?
___
*[`store/eth_data.go` line 23 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdTp7d-C94hOiraP3Yn:-NdTp7d0516qGqWZwdQX:b2gqsvh) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5013ad0a6eb2ce17e3d74a8bfb3d5f9652572a4/store/eth_data.go#L23)):*
> ```Go
> 	// get block
> 	block, err := w3c.Eth.BlockByNumber(types.BlockNumber(blockNumber), true)
> 	if err == nil && block == nil {
> ```

Why not handle `err != nil` condition at first?

On the other hand, how about to return `nil` data instead of `error`? Because, the error handling may be totally different.
___
*[`store/eth_data.go` line 32 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdTqFzC7vX0EyLVrHsy:-NdTqFzC7vX0EyLVrHsz:bpcoups) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5013ad0a6eb2ce17e3d74a8bfb3d5f9652572a4/store/eth_data.go#L32)):*
> ```Go
> 	// batch get receipts
> 	var blockReceipts []types.Receipt
> 	if useBatch {
> ```

Why not use batch rpc all the time?



_Code quote:_
```Go
useBatch
```
___
*[`store/eth_data.go` line 34 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdTqa0Q5qm6LEWM6pPX:-NdTqa0Q5qm6LEWM6pPY:b-ivz0r) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5013ad0a6eb2ce17e3d74a8bfb3d5f9652572a4/store/eth_data.go#L34)):*
> ```Go
> 	if useBatch {
> 		blockNumOrHash := types.BlockNumberOrHashWithNumber(types.BlockNumber(blockNumber))
> 		blockReceipts, err = w3c.Parity.BlockReceipts(&blockNumOrHash)
> ```

Why query for all receipts of specific block? Instead, only required event logs are enough.

DO NOT COPY PASTE ALL THE TIME!



_Code quote:_
```Go
BlockReceipts
```
___
*[`store/store_block.go` line 72 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdTriHo2Y8it8upJeLh:-NdTriHo2Y8it8upJeLi:bwf3iym) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5013ad0a6eb2ce17e3d74a8bfb3d5f9652572a4/store/store_block.go#L72)):*
> ```Go
> 
> func (bs *blockStore) Remove(dbTx *gorm.DB, block uint64) error {
> 	return dbTx.Where("block_number = ?", block).Delete(&Block{}).Error
> ```

Only remove a single block?
___
*[`store/store_submit.go` line 56 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdTs4zZEGIfU2IeYeSu:-NdTs4zZEGIfU2IeYeSv:bqjcvfm) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5013ad0a6eb2ce17e3d74a8bfb3d5f9652572a4/store/store_submit.go#L56)):*
> ```Go
> 	as            *addressStore
> 	flowAddr      string
> 	flowSubmitSig string
> ```

Maybe flow contract address as log filter is enough, and query all event logs by default.
___
*[`store/store_submit.go` line 87 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdTsPH10I_IMe6r6Tal:-NdTsPH10I_IMe6r6Tam:bul2ayn) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5013ad0a6eb2ce17e3d74a8bfb3d5f9652572a4/store/store_submit.go#L87)):*
> ```Go
> 			contract := log.Address.String()
> 			topic0 := log.Topics[0].String()
> 			if !strings.EqualFold(contract, ss.flowAddr) || topic0 != ss.flowSubmitSig {
> ```

Instead, using log filte to query event logs is more efficient.
___
*[`store/store_submit.go` line 114 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdTsYPt2aMPey09okcH:-NdTsYPt2aMPey09okcI:b-plhaej) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5013ad0a6eb2ce17e3d74a8bfb3d5f9652572a4/store/store_submit.go#L114)):*
> ```Go
> 
> func (ss *submitStore) Remove(dbTx *gorm.DB, block uint64) error {
> 	return dbTx.Where("block_number = ?", block).Delete(&Submit{}).Error
> ```

Only remove event logs of specific block?
___
*[`sync/sync.go` line 17 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdTt7jlCRxOMDdsh3I1:-NdTt7jlCRxOMDdsh3I2:boeaw27) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5013ad0a6eb2ce17e3d74a8bfb3d5f9652572a4/sync/sync.go#L17)):*
> ```Go
> 	BlockWhenFlowCreated  uint64
> 	SkipBlocksAheadLatest uint64
> 	UseBatch              bool
> ```

In my mind, this is not required anymore, you could confirm wth Liqun.



_Code quote:_
```Go
UseBatch
```
___
*[`sync/sync.go` line 32 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdTtRR_AoEWc7nsiyfR:-NdTtRR_AoEWc7nsiyfS:b-pvde83) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5013ad0a6eb2ce17e3d74a8bfb3d5f9652572a4/sync/sync.go#L32)):*
> ```Go
> func MustNewSyncer(sdk *web3go.Client, db *store.MysqlStore) *Syncer {
> 	var conf syncConfig
> 	viperutil.MustUnmarshalKey("sync", &conf)
> ```

In fact, this is not a good practice to create a `syncer` instance. Strongly recommend to change to `MustNewSyncer(sdk, db, config)`, and let caller to load `config` from viper.
___
*[`sync/sync.go` line 93 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdTuqSK-BxJHSDdnPqt:-NdTuqSK-BxJHSDdnPqu:b-wedkug) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5013ad0a6eb2ce17e3d74a8bfb3d5f9652572a4/sync/sync.go#L93)):*
> ```Go
> 				logrus.WithError(err).
> 					WithField("currentBlock", s.currentBlock).
> 					Error("Syncer failed to sync eth data")
> ```

Once failed, the sync routine will retry after several seconds, so `WARNING` level is enough.
___
*[`sync/sync.go` line 136 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdTvN0GCxiZusZB_LIs:-NdTvN0GCxiZusZB_LIt:b9net5h) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5013ad0a6eb2ce17e3d74a8bfb3d5f9652572a4/sync/sync.go#L136)):*
> ```Go
> 	if err != nil {
> 		return false, errors.WithMessagef(err, "[Syncer]get eth data at block %v failure", curBlock)
> 	}
> ```

Any different between `ErrChainReorged` and othe kinds of erros?
___
*[`sync/sync.go` line 138 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdTw9AX9RBUjngV2bmW:-NdTw9AX9RBUjngV2bmX:bpt741j) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5013ad0a6eb2ce17e3d74a8bfb3d5f9652572a4/sync/sync.go#L138)):*
> ```Go
> 	}
> 
> 	// check pivot hash
> ```

Is it unnecessary before `latest_finalized` block number.
___
*[`sync/sync.go` line 159 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdTwEGL5Eout5B86H7U:-NdTwEGL5Eout5B86H7V:b-sokk43) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5013ad0a6eb2ce17e3d74a8bfb3d5f9652572a4/sync/sync.go#L159)):*
> ```Go
> 	s.currentBlock += 1
> 
> 	return true, nil
> ```

return `false`?


<!-- Sent from Reviewable.io -->

2023-09-04 06:48 UTC, boqiu reviewed
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3)* status: all files reviewed, 14 unresolved discussions (waiting on @Argeric and @wanliqun)



<!-- Sent from Reviewable.io -->

2023-09-04 07:01 UTC, wanliqun requested changes
> Reviewed 3 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3)* status: all files reviewed, 26 unresolved discussions (waiting on @Argeric)

___
*[`config/config.yml` line 5 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdTIvrm4Q-1P7-72LBs:-NdTIvrm4Q-1P7-72LBt:bejnivc) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5013ad0a6eb2ce17e3d74a8bfb3d5f9652572a4/config/config.yml#L5)):*
> ```YAML
>   blockWhenFlowCreated: 136228690
>   skipBlocksAheadLatest: 32
>   useBatch: true
> ```

Better to add more comments.



_Code quote:_
```YAML
  skipBlocksAheadLatest: 32
  useBatch: true
```
___
*[`config/config.yml` line 15 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdTIOLg8p24-yCE38wT:-NdTIOLg8p24-yCE38wU:bv6jkx) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5013ad0a6eb2ce17e3d74a8bfb3d5f9652572a4/config/config.yml#L15)):*
> ```YAML
> store:
>   mysql:
>     enabled: true
> ```

Isn't `mysql` a must?
___
*[`config/config.yml` line 22 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdTJsBIE2Ba8ThM1w1B:-NdTJsBIE2Ba8ThM1w1C:b-ggo05h) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5013ad0a6eb2ce17e3d74a8bfb3d5f9652572a4/config/config.yml#L22)):*
> ```YAML
>     connMaxLifeTime: 3m
>     maxOpenConns: 10
>     maxIdleConns: 10
> ```

Could be commented out if a decent default value provided.



_Code quote:_
```YAML
    connMaxLifeTime: 3m
    maxOpenConns: 10
    maxIdleConns: 10
```
___
*[`store/eth_data.go` line 32 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdTm4SoBlWTP_pyPde6:-NdTm4SoBlWTP_pyPde7:b-1ep5it) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5013ad0a6eb2ce17e3d74a8bfb3d5f9652572a4/store/eth_data.go#L32)):*
> ```Go
> 	// batch get receipts
> 	var blockReceipts []types.Receipt
> 	if useBatch {
> ```

Possible to split two sub-functions for both batch receipt and receipt per txn versions?
___
*[`store/eth_data.go` line 72 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdTlr2iBdwoHqEYgb8V:-NdTlr2iBdwoHqEYgb8W:bt4ynn1) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5013ad0a6eb2ce17e3d74a8bfb3d5f9652572a4/store/eth_data.go#L72)):*
> ```Go
> 				receipt.BlockNumber, blockNumber)
> 		case receipt.TransactionHash != txHash:
> 			err = errors.WithMessagef(ErrChainReorged, "receipt tx hash mismatch, rcptTxHash %v, TxHash %v",
> ```

We might return out of this function directly, so the err nil check is not needed below.
___
*[`store/store.go` line 64 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdTmzdW4onxCUCObsPU:-NdTmzdW4onxCUCObsPV:b-nzh1xp) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5013ad0a6eb2ce17e3d74a8bfb3d5f9652572a4/store/store.go#L64)):*
> ```Go
> 		}
> 		if err := ms.submitStore.Remove(dbTx, block); err != nil {
> 			return errors.WithMessage(err, "failed to remove submit logs")
> ```

Better to use error msg `failed to remove flow submits`
___
*[`store/store_block.go` line 72 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdTnVPx9CCbaylF_um4:-NdTnVPx9CCbaylF_um5:b-jk94bf) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5013ad0a6eb2ce17e3d74a8bfb3d5f9652572a4/store/store_block.go#L72)):*
> ```Go
> 
> func (bs *blockStore) Remove(dbTx *gorm.DB, block uint64) error {
> 	return dbTx.Where("block_number = ?", block).Delete(&Block{}).Error
> ```

When do poping due to pivot chain, removing a single block is not enough. We might need to remove by a block range instead.
___
*[`store/store_submit.go` line 114 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdTpQfT835h2g2YUT_z:-NdTpQfT835h2g2YUTa-:b-7ropln) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5013ad0a6eb2ce17e3d74a8bfb3d5f9652572a4/store/store_submit.go#L114)):*
> ```Go
> 
> func (ss *submitStore) Remove(dbTx *gorm.DB, block uint64) error {
> 	return dbTx.Where("block_number = ?", block).Delete(&Submit{}).Error
> ```

ditto
___
*[`sync/sync.go` line 16 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdTpxzf7kdNgnnhZ4Au:-NdTpxzf7kdNgnnhZ4Av:b-tnc7is) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5013ad0a6eb2ce17e3d74a8bfb3d5f9652572a4/sync/sync.go#L16)):*
> ```Go
> type syncConfig struct {
> 	BlockWhenFlowCreated  uint64
> 	SkipBlocksAheadLatest uint64
> ```

You may set a default config vaue with  a`default` struct tag
```
type syncConfig struct {
...
	SkipBlocksAheadLatest uint64 \`default:"30"\`
...
```
___
*[`sync/sync.go` line 29 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdTrl0F-1TJ-Q-7kSjC:-NdTrl0F-1TJ-Q-7kSjD:b-g3vsgz) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5013ad0a6eb2ce17e3d74a8bfb3d5f9652572a4/sync/sync.go#L29)):*
> ```Go
> }
> 
> // MustNewSyncer creates an instance of DatabaseSyncer to sync blockchain data.
> ```

`DatabaseSyncer`?
___
*[`sync/sync.go` line 38 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdTrzD1Bb2azblsVEjz:-NdTrzD1Bb2azblsVEk-:bvgchjb) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5013ad0a6eb2ce17e3d74a8bfb3d5f9652572a4/sync/sync.go#L38)):*
> ```Go
> 		sdk:                 sdk,
> 		db:                  db,
> 		currentBlock:        0,
> ```

As golang will initialze default zero value, setting `currentBlock` to 0 is not necessary.
___
*[`sync/sync.go` line 164 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdTz-SACfWMPpLKXCiP:-NdTz-SACfWMPpLKXCiQ:b-7fk8tr) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5013ad0a6eb2ce17e3d74a8bfb3d5f9652572a4/sync/sync.go#L164)):*
> ```Go
> func (s *Syncer) getStoreLatestBlockHash() (string, error) {
> 	blockFlowContractCreated := s.conf.BlockWhenFlowCreated
> 	if s.currentBlock == blockFlowContractCreated {
> ```

s.currentBlock <= blockFlowContractCreated?


<!-- Sent from Reviewable.io -->

2023-09-04 07:19 UTC, wanliqun reviewed
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3)* status: all files reviewed, 26 unresolved discussions (waiting on @Argeric and @boqiu)

___
*[`sync/sync.go` line 17 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdTt7jlCRxOMDdsh3I1:-NdU-XYlCiVtKlFy64bn:b-bniluq) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5013ad0a6eb2ce17e3d74a8bfb3d5f9652572a4/sync/sync.go#L17)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

In my mind, this is not required anymore, you could confirm wth Liqun.
</blockquote></details>

Yes, `parity_blockReceipts` debug RPC method is fully ready now. We used `UseBatch` switch in `Confura` due to it was added during our dev.


<!-- Sent from Reviewable.io -->

2023-09-04 07:23 UTC, wanliqun commented
*[`store/eth_data.go` line 32 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdTm4SoBlWTP_pyPde6:-NdU369C58rY1aNVOLDb:beupvhj) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5013ad0a6eb2ce17e3d74a8bfb3d5f9652572a4/store/eth_data.go#L32)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></summary><blockquote>

Possible to split two sub-functions for both batch receipt and receipt per txn versions?
</blockquote></details>

deprecated if only batch receipts are needed.


<!-- Sent from Reviewable.io -->

2023-09-04 08:44 UTC, Argeric reviewed
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3)* status: all files reviewed, 25 unresolved discussions (waiting on @boqiu and @wanliqun)

___
*[`config/config.yml` line 5 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdTIvrm4Q-1P7-72LBs:-NdU1wg5BXokVER0Pg-5:b-7tfmjp) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5013ad0a6eb2ce17e3d74a8bfb3d5f9652572a4/config/config.yml#L5)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></summary><blockquote>

Better to add more comments.
</blockquote></details>

added
___
*[`config/config.yml` line 15 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdTIOLg8p24-yCE38wT:-NdU1yfG1n4ZZ-f1j10j:b-p18ixb) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5013ad0a6eb2ce17e3d74a8bfb3d5f9652572a4/config/config.yml#L15)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></summary><blockquote>

Isn't `mysql` a must?
</blockquote></details>

not must ,already removed
___
*[`config/config.yml` line 22 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdTJsBIE2Ba8ThM1w1B:-NdU229iAznnGCMQgZ9l:b2nign6) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5013ad0a6eb2ce17e3d74a8bfb3d5f9652572a4/config/config.yml#L22)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></summary><blockquote>

Could be commented out if a decent default value provided.
</blockquote></details>

yes
___
*[`store/eth_data.go` line 22 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdTpzCLE4vqAjR6K9_1:-NdU2ckYECqbo3rT665y:br6ziuo) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5013ad0a6eb2ce17e3d74a8bfb3d5f9652572a4/store/eth_data.go#L22)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Is it necessary to return all transactions?
</blockquote></details>

Using all transactions in a block to check if re-org happens with all receipts in a block for the different rpc methods are not atomic.
___
*[`store/eth_data.go` line 23 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdTp7d-C94hOiraP3Yn:-NdU4Ou56c47CBevRmmV:b-8qu0a3) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5013ad0a6eb2ce17e3d74a8bfb3d5f9652572a4/store/eth_data.go#L23)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Why not handle `err != nil` condition at first?

On the other hand, how about to return `nil` data instead of `error`? Because, the error handling may be totally different.
</blockquote></details>

en, it also could be better to handle err != nill and something like as follows
if err != nil {  
   return nil, errors.WithMessagef(err, "failed to get block by number %v", blockNumber)  
}  
if block == nil {  
   return nil, errors.WithMessagef(err, "block is nil at block number %v", blockNumber)  
}
___
*[`store/eth_data.go` line 32 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdTqFzC7vX0EyLVrHsy:-NdU58zt6AklaK0fYtAB:b-eumg9a) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5013ad0a6eb2ce17e3d74a8bfb3d5f9652572a4/store/eth_data.go#L32)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Why not use batch rpc all the time?
</blockquote></details>

fixed to use batch rpc
___
*[`store/eth_data.go` line 32 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdTm4SoBlWTP_pyPde6:-NdU5gIiE3Fal5KxAcFL:b-eumg9a) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5013ad0a6eb2ce17e3d74a8bfb3d5f9652572a4/store/eth_data.go#L32)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></summary><blockquote>

deprecated if only batch receipts are needed.
</blockquote></details>

fixed to use batch rpc
___
*[`store/eth_data.go` line 34 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdTqa0Q5qm6LEWM6pPX:-NdU5i0G6QPxxl2pbj_s:bem2x8) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5013ad0a6eb2ce17e3d74a8bfb3d5f9652572a4/store/eth_data.go#L34)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Why query for all receipts of specific block? Instead, only required event logs are enough.

DO NOT COPY PASTE ALL THE TIME!
</blockquote></details>

Using all receipts in a block to check if reorg happens with all transactions in a block, and only event logs can not checkout re-org.
___
*[`store/eth_data.go` line 47 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#gh-1314468362:-NdU93NY9holS6PUcqOz:bc4ypvz) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5013ad0a6eb2ce17e3d74a8bfb3d5f9652572a4/store/eth_data.go#L47)):*
<details><summary><i>Previously, Tigo9527 wrote…</i></summary><blockquote>

Better to check it before `for` loop
</blockquote></details>

yes, moved out of for loop
___
*[`store/eth_data.go` line 72 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdTlr2iBdwoHqEYgb8V:-NdUEP7P3ukU1NGdRcQD:b-7ql1td) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5013ad0a6eb2ce17e3d74a8bfb3d5f9652572a4/store/eth_data.go#L72)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></summary><blockquote>

We might return out of this function directly, so the err nil check is not needed below.
</blockquote></details>

fixed
___
*[`store/store.go` line 64 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdTmzdW4onxCUCObsPU:-NdUFzsG86UEpQ5CGOHV:b-7ql1td) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5013ad0a6eb2ce17e3d74a8bfb3d5f9652572a4/store/store.go#L64)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></summary><blockquote>

Better to use error msg `failed to remove flow submits`
</blockquote></details>

fixed
___
*[`store/store_block.go` line 72 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdTriHo2Y8it8upJeLh:-NdUD5ZzAFKHSzXhKAhh:b-7ql1td) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5013ad0a6eb2ce17e3d74a8bfb3d5f9652572a4/store/store_block.go#L72)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Only remove a single block?
</blockquote></details>

fixed
___
*[`store/store_block.go` line 72 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdTnVPx9CCbaylF_um4:-NdUD7m92U3G8NMYy4J9:b-7ql1td) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5013ad0a6eb2ce17e3d74a8bfb3d5f9652572a4/store/store_block.go#L72)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></summary><blockquote>

When do poping due to pivot chain, removing a single block is not enough. We might need to remove by a block range instead.
</blockquote></details>

fixed
___
*[`store/store_submit.go` line 56 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdTs4zZEGIfU2IeYeSu:-NdUG1XhAZn2PCW870Gr:b-54olpr) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5013ad0a6eb2ce17e3d74a8bfb3d5f9652572a4/store/store_submit.go#L56)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Maybe flow contract address as log filter is enough, and query all event logs by default.
</blockquote></details>

When checking pivot switch, the receipts have been already fetched which contains event logs. The log filter can be used in catchup syncing mode.
___
*[`store/store_submit.go` line 87 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdTsPH10I_IMe6r6Tal:-NdUGzqj4dcHFgOFzjoE:bdn8e21) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5013ad0a6eb2ce17e3d74a8bfb3d5f9652572a4/store/store_submit.go#L87)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Instead, using log filte to query event logs is more efficient.
</blockquote></details>

We need receipts to chec [...]

2023-09-04 09:16 UTC, boqiu requested changes
> Reviewed 4 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3)* status: all files reviewed, 13 unresolved discussions (waiting on @Argeric and @wanliqun)

___
*[`store/eth_data.go` line 22 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdTpzCLE4vqAjR6K9_1:-NdUQzO_ArWu2xy9xKaF:b-ts8l43) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5013ad0a6eb2ce17e3d74a8bfb3d5f9652572a4/store/eth_data.go#L22)):*
<details><summary><i>Previously, Argeric wrote…</i></summary><blockquote>

Using all transactions in a block to check if re-org happens with all receipts in a block for the different rpc methods are not atomic.
</blockquote></details>

Tx hash is enough, is it?
___
*[`store/eth_data.go` line 34 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdTqa0Q5qm6LEWM6pPX:-NdURVSw5nTnTGVbO0_s:b-x4ydhy) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5013ad0a6eb2ce17e3d74a8bfb3d5f9652572a4/store/eth_data.go#L34)):*
<details><summary><i>Previously, Argeric wrote…</i></summary><blockquote>

Using all receipts in a block to check if reorg happens with all transactions in a block, and only event logs can not checkout re-org.
</blockquote></details>

I think a better way for chain reorg detection is to check block number, hash and parent hash. 
___
*[`store/eth_data.go` line 27 at r2](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdURK8S8OaFrrE2rq-U:-NdURK8S8OaFrrE2rq-V:bfch8bi) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/68f4dfaea9c3281a4661106da274aababa3553ef/store/eth_data.go#L27)):*
> ```Go
> 	}
> 	if block == nil {
> 		return nil, errors.WithMessagef(err, "block is nil at block number %v", blockNumber)
> ```

Recommend to return `nil` value instead of `error`, because it is a normal case, not an error.
___
*[`store/store_block.go` line 72 at r2](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdUSgvOAzVR0iPss5-V:-NdUSgvOAzVR0iPss5-W:bb7bh5y) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/68f4dfaea9c3281a4661106da274aababa3553ef/store/store_block.go#L72)):*
> ```Go
> 
> func (bs *blockStore) Remove(dbTx *gorm.DB, block uint64) error {
> 	return dbTx.Where("block_number <= ?", block).Delete(&Block{}).Error
> ```

`>=`
___
*[`store/store_submit.go` line 56 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdTs4zZEGIfU2IeYeSu:-NdUS4zX8UodWOvGgUcX:b-c88tnt) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5013ad0a6eb2ce17e3d74a8bfb3d5f9652572a4/store/store_submit.go#L56)):*
<details><summary><i>Previously, Argeric wrote…</i></summary><blockquote>

When checking pivot switch, the receipts have been already fetched which contains event logs. The log filter can be used in catchup syncing mode.
</blockquote></details>

Why not using `eth_getLogs` to sync event logs, which is more light weight?
___
*[`store/store_submit.go` line 87 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdTsPH10I_IMe6r6Tal:-NdUSIno36di8ycbxWlI:b-kcabah) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5013ad0a6eb2ce17e3d74a8bfb3d5f9652572a4/store/store_submit.go#L87)):*
<details><summary><i>Previously, Argeric wrote…</i></summary><blockquote>

We need receipts to check pivot switch , and event logs contained in receipt can be used
</blockquote></details>

Maybe you could have a off-line discussion with Liqun for chain reorg detection.
___
*[`store/store_submit.go` line 114 at r2](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdUSVis0bJLOet2QO8B:-NdUSVis0bJLOet2QO8C:b-w3u2fp) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/68f4dfaea9c3281a4661106da274aababa3553ef/store/store_submit.go#L114)):*
> ```Go
> 
> func (ss *submitStore) Remove(dbTx *gorm.DB, block uint64) error {
> 	return dbTx.Where("block_number <= ?", block).Delete(&Submit{}).Error
> ```

`>=` ?

Please pay more attention about code quality.
___
*[`sync/sync.go` line 136 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdTvN0GCxiZusZB_LIs:-NdUT16j-SibcbKI7X6n:b-7o0xuq) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5013ad0a6eb2ce17e3d74a8bfb3d5f9652572a4/sync/sync.go#L136)):*
<details><summary><i>Previously, Argeric wrote…</i></summary><blockquote>

ErrChainReorged will be returned when receipts and transatcionts from different rpc not match, and other errors will be returned when single rpc method return error.
</blockquote></details>

Why not return `err` directly?
___
*[`sync/sync.go` line 138 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdTw9AX9RBUjngV2bmW:-NdUTA6-EeeDj12jRc3b:brld3es) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5013ad0a6eb2ce17e3d74a8bfb3d5f9652572a4/sync/sync.go#L138)):*
<details><summary><i>Previously, Argeric wrote…</i></summary><blockquote>

The normal mode syncing needs checking pivot switch. The catchup mod syncing might be unnecessary.
</blockquote></details>

So, this is only for normal sync phase, right?
___
*[`sync/sync.go` line 159 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdTwEGL5Eout5B86H7U:-NdUTMPk0OBUgrFKB5YS:b-u01ma6) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5013ad0a6eb2ce17e3d74a8bfb3d5f9652572a4/sync/sync.go#L159)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></summary><blockquote>

Seems a `true` return signifies the sync has already catches up.
</blockquote></details>

When return `true`, the syncer will sleep `1s`, which is unnecessary if any block synced.
___
*[`sync/sync.go` line 28 at r2](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdUStLO9tIoAgPTHcyh:-NdUStLO9tIoAgPTHcyi:bjhu1wh) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/68f4dfaea9c3281a4661106da274aababa3553ef/sync/sync.go#L28)):*
> ```Go
> 
> // MustNewSyncer creates an instance of Syncer to sync blockchain data.
> func MustNewSyncer(sdk *web3go.Client, db *store.MysqlStore, conf syncConfig) *Syncer {
> ```

`syncConfig` struct should be changed to `public`.


<!-- Sent from Reviewable.io -->

2023-09-04 09:17 UTC, Argeric reviewed
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3)* status: all files reviewed, 13 unresolved discussions (waiting on @boqiu and @wanliqun)

___
*[`store/store_submit.go` line 56 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdTs4zZEGIfU2IeYeSu:-NdUTiCD8ojcg-X2jTyD:blvjmhb) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5013ad0a6eb2ce17e3d74a8bfb3d5f9652572a4/store/store_submit.go#L56)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Why not using `eth_getLogs` to sync event logs, which is more light weight?
</blockquote></details>

only using eth_getlogs cannot process reorg


<!-- Sent from Reviewable.io -->

2023-09-04 09:17 UTC, Argeric reviewed
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3)* status: all files reviewed, 13 unresolved discussions (waiting on @boqiu and @wanliqun)

___
*[`store/store_submit.go` line 87 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdTsPH10I_IMe6r6Tal:-NdUTsU_9KxmTIigha71:b32wtd) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5013ad0a6eb2ce17e3d74a8bfb3d5f9652572a4/store/store_submit.go#L87)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Maybe you could have a off-line discussion with Liqun for chain reorg detection.
</blockquote></details>

ok


<!-- Sent from Reviewable.io -->

2023-09-04 09:18 UTC, Argeric reviewed
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3)* status: all files reviewed, 13 unresolved discussions (waiting on @boqiu and @wanliqun)

___
*[`store/store_submit.go` line 114 at r2](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdUSVis0bJLOet2QO8B:-NdUU-Wd3BLqXKHFO0ym:b2ni9b3) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/68f4dfaea9c3281a4661106da274aababa3553ef/store/store_submit.go#L114)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

`>=` ?

Please pay more attention about code quality.
</blockquote></details>

ok 


<!-- Sent from Reviewable.io -->

2023-09-04 09:19 UTC, Argeric reviewed
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3)* status: 4 of 6 files reviewed, 13 unresolved discussions (waiting on @boqiu and @wanliqun)

___
*[`sync/sync.go` line 28 at r2](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdUStLO9tIoAgPTHcyh:-NdUUArN1y2F0ib9HchP:b-qssecl) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/68f4dfaea9c3281a4661106da274aababa3553ef/sync/sync.go#L28)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

`syncConfig` struct should be changed to `public`.
</blockquote></details>

fixed


<!-- Sent from Reviewable.io -->

2023-09-04 09:20 UTC, Argeric reviewed
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3)* status: 3 of 6 files reviewed, 13 unresolved discussions (waiting on @boqiu and @wanliqun)

___
*[`sync/sync.go` line 136 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdTvN0GCxiZusZB_LIs:-NdUUQJsB_TRRTgSgSUB:bhug20c) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5013ad0a6eb2ce17e3d74a8bfb3d5f9652572a4/sync/sync.go#L136)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Why not return `err` directly?
</blockquote></details>

Using different message can easily check reason


<!-- Sent from Reviewable.io -->

2023-09-04 09:21 UTC, Argeric reviewed
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3)* status: 3 of 6 files reviewed, 13 unresolved discussions (waiting on @boqiu and @wanliqun)

___
*[`sync/sync.go` line 138 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdTw9AX9RBUjngV2bmW:-NdUUhE08H8RL2Wf9sI2:b2nign6) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5013ad0a6eb2ce17e3d74a8bfb3d5f9652572a4/sync/sync.go#L138)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

So, this is only for normal sync phase, right?
</blockquote></details>

yes


<!-- Sent from Reviewable.io -->

2023-09-04 10:54 UTC, Argeric reviewed
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3)* status: 3 of 6 files reviewed, 13 unresolved discussions (waiting on @boqiu and @wanliqun)

___
*[`store/eth_data.go` line 22 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdTpzCLE4vqAjR6K9_1:-NdUjaCT3bvwsUOcKEdp:bik8c0p) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5013ad0a6eb2ce17e3d74a8bfb3d5f9652572a4/store/eth_data.go#L22)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Tx hash is enough, is it?
</blockquote></details>

As we discussed offline，we need at present
___
*[`store/eth_data.go` line 34 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdTqa0Q5qm6LEWM6pPX:-NdUkx_W8fFP07jWeXNZ:b-pf1mxn) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5013ad0a6eb2ce17e3d74a8bfb3d5f9652572a4/store/eth_data.go#L34)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

I think a better way for chain reorg detection is to check block number, hash and parent hash.
</blockquote></details>

As we discussed offline，checking re-org between receipts and txs is best practice at present.
___
*[`store/eth_data.go` line 27 at r2](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdURK8S8OaFrrE2rq-U:-NdUmoM6EoNtXWsQZegG:b-mesvq2) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/68f4dfaea9c3281a4661106da274aababa3553ef/store/eth_data.go#L27)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Recommend to return `nil` value instead of `error`, because it is a normal case, not an error.
</blockquote></details>

I think they are all errors for querying block instance by block number, which can also simplify process logic.
___
*[`store/store_block.go` line 72 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdTnVPx9CCbaylF_um4:-NdUl-hjCHY8RAvpTPVM:b-71b3dl) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5013ad0a6eb2ce17e3d74a8bfb3d5f9652572a4/store/store_block.go#L72)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></summary><blockquote>

This doesn't seem right as you would remove all data with block number less than the reorg point (let's say you had synchronized for a while already). Maybe you can use parameter to specify a block range to delete or define a `popUntil` function instead to remove all data wth block number greater than or equal the reorg point.
</blockquote></details>

As we discussed offline，we process block by block
___
*[`store/store_block.go` line 72 at r2](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdUSgvOAzVR0iPss5-V:-NdUl6NKDx5takxC1xfC:b-71b3dl) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/68f4dfaea9c3281a4661106da274aababa3553ef/store/store_block.go#L72)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

`>=`
</blockquote></details>

As we discussed offline，we process block by block
___
*[`store/store_submit.go` line 87 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdTsPH10I_IMe6r6Tal:-NdUlAN56fLESASwIRh4:bh1sf1t) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5013ad0a6eb2ce17e3d74a8bfb3d5f9652572a4/store/store_submit.go#L87)):*
<details><summary><i>Previously, Argeric wrote…</i></summary><blockquote>

ok
</blockquote></details>

As we discussed offline，we use existing re-org checking logic
___
*[`store/store_submit.go` line 114 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdTpQfT835h2g2YUT_z:-NdUlh4rE-UF22sLud3Z:b-71b3dl) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5013ad0a6eb2ce17e3d74a8bfb3d5f9652572a4/store/store_submit.go#L114)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

As we discussed offline，we process block by block
___
*[`store/store_submit.go` line 114 at r2](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdUSVis0bJLOet2QO8B:-NdUli5L8aBF2C-fSM5D:b-71b3dl) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/68f4dfaea9c3281a4661106da274aababa3553ef/store/store_submit.go#L114)):*
<details><summary><i>Previously, Argeric wrote…</i></summary><blockquote>

ok
</blockquote></details>

As we discussed offline，we process block by block
___
*[`sync/sync.go` line 159 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdTwEGL5Eout5B86H7U:-NdUnMKS32GLydOoVReV:b-tt9gxw) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5013ad0a6eb2ce17e3d74a8bfb3d5f9652572a4/sync/sync.go#L159)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

When return `true`, the syncer will sleep `1s`, which is unnecessary if any block synced.
</blockquote></details>

I think its ok in normal syncing mode against latest block number.


<!-- Sent from Reviewable.io -->

2023-09-04 11:08 UTC, boqiu requested changes
> Reviewed 1 of 1 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3)* status: all files reviewed, 8 unresolved discussions (waiting on @Argeric and @wanliqun)

___
*[`store/eth_data.go` line 22 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdTpzCLE4vqAjR6K9_1:-NdUs4Vk098DCJnX7ybr:bdav5tt) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5013ad0a6eb2ce17e3d74a8bfb3d5f9652572a4/store/eth_data.go#L22)):*
<details><summary><i>Previously, Argeric wrote…</i></summary><blockquote>

As we discussed offline，we need at present
</blockquote></details>

But I did not see any usage of tx body?
___
*[`store/eth_data.go` line 34 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdTqa0Q5qm6LEWM6pPX:-NdUpvu72Od6cj3cPPQ4:bklm1g9) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5013ad0a6eb2ce17e3d74a8bfb3d5f9652572a4/store/eth_data.go#L34)):*
<details><summary><i>Previously, Argeric wrote…</i></summary><blockquote>

As we discussed offline，checking re-org between receipts and txs is best practice at present.
</blockquote></details>

But I did not see any usage for tx body, only tx hash used.
___
*[`store/eth_data.go` line 27 at r2](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdURK8S8OaFrrE2rq-U:-NdUsLZ16iBEn_sHZxLn:bg3jl8c) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/68f4dfaea9c3281a4661106da274aababa3553ef/store/eth_data.go#L27)):*
<details><summary><i>Previously, Argeric wrote…</i></summary><blockquote>

I think they are all errors for querying block instance by block number, which can also simplify process logic.
</blockquote></details>

For any error (unexpected), sync layer may add `error` log and alert. When it comes to `nil` case, sync layer may just sleep for a while.
___
*[`store/store_block.go` line 72 at r2](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdUSgvOAzVR0iPss5-V:-NdUqPCz9wAtA05dHQTj:b-skb6dz) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/68f4dfaea9c3281a4661106da274aababa3553ef/store/store_block.go#L72)):*
<details><summary><i>Previously, Argeric wrote…</i></summary><blockquote>

As we discussed offline，we process block by block
</blockquote></details>

I strongly recommend to use `>=`, which is also valid for block by block case. In this way, even any bug occurred at sync layer, the data in db is still correct. Data safe is really important.

On the other hand, maybe `pop` is a better name.
___
*[`store/store_submit.go` line 114 at r2](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdUSVis0bJLOet2QO8B:-NdUrT7h1GkB5nezXh47:b-11szja) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/68f4dfaea9c3281a4661106da274aababa3553ef/store/store_submit.go#L114)):*
<details><summary><i>Previously, Argeric wrote…</i></summary><blockquote>

As we discussed offline，we process block by block
</blockquote></details>

The same with previous comment for data safe purpose.
___
*[`sync/sync.go` line 136 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdTvN0GCxiZusZB_LIs:-NdUrakYAhGY4dK02UAr:bk5nfvh) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5013ad0a6eb2ce17e3d74a8bfb3d5f9652572a4/sync/sync.go#L136)):*
<details><summary><i>Previously, Argeric wrote…</i></summary><blockquote>

Using different message can easily check reason
</blockquote></details>

the `err` itself alreays contains concrete reason.


<!-- Sent from Reviewable.io -->

2023-09-05 02:09 UTC, wanliqun reviewed
> Reviewed 2 of 2 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3)* status: all files reviewed, 6 unresolved discussions (waiting on @Argeric)

___
*[`sync/sync.go` line 159 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdTwEGL5Eout5B86H7U:-NdY3Hs89YUsemn4xse2:b-83mkei) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5013ad0a6eb2ce17e3d74a8bfb3d5f9652572a4/sync/sync.go#L159)):*
<details><summary><i>Previously, Argeric wrote…</i></summary><blockquote>

I think its ok in normal syncing mode against latest block number.
</blockquote></details>

Let's say you are syncing blocks one by one, and your current block is 10 blocks behind the latest block number. If you return `true` here, you might never have a chance to catch up to the latest block number since the sync interval is set to 1s.


<!-- Sent from Reviewable.io -->

2023-09-05 02:23 UTC, wanliqun requested changes
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3)* status: all files reviewed, 7 unresolved discussions (waiting on @Argeric)

___
*[`sync/sync.go` line 159 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdTwEGL5Eout5B86H7U:-NdY83q_3cBJZUtDdZt6:b1ib88o) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5013ad0a6eb2ce17e3d74a8bfb3d5f9652572a4/sync/sync.go#L159)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></summary><blockquote>

Let's say you are syncing blocks one by one, and your current block is 10 blocks behind the latest block number. If you return `true` here, you might never have a chance to catch up to the latest block number since the sync interval is set to 1s.
</blockquote></details>

I think this could lead to considerable lags.


<!-- Sent from Reviewable.io -->

2023-09-05 03:15 UTC, Argeric reviewed
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3)* status: all files reviewed, 7 unresolved discussions (waiting on @boqiu and @wanliqun)

___
*[`store/eth_data.go` line 22 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdTpzCLE4vqAjR6K9_1:-NdYD1EwCz1Fjk7rEFCH:bx1amd7) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5013ad0a6eb2ce17e3d74a8bfb3d5f9652572a4/store/eth_data.go#L22)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

But I did not see any usage of tx body?
</blockquote></details>

Yes, changed to use false isFull parameter
___
*[`store/eth_data.go` line 34 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdTqa0Q5qm6LEWM6pPX:-NdYKIi3-Mz1XIvx4lod:b-sn1y5t) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5013ad0a6eb2ce17e3d74a8bfb3d5f9652572a4/store/eth_data.go#L34)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

But I did not see any usage for tx body, only tx hash used.
</blockquote></details>

Yes, we just use tx hash to check reorg, and BlockReceipts(&blockNumOrHash) rpc method does not support 'isFull' parameter for now.
___
*[`store/eth_data.go` line 27 at r2](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdURK8S8OaFrrE2rq-U:-NdYIOXo5Uht8rOvOerw:b-7ql1td) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/68f4dfaea9c3281a4661106da274aababa3553ef/store/eth_data.go#L27)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

For any error (unexpected), sync layer may add `error` log and alert. When it comes to `nil` case, sync layer may just sleep for a while.
</blockquote></details>

fixed
___
*[`store/store_block.go` line 72 at r2](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdUSgvOAzVR0iPss5-V:-NdYDt97BuQtGFVAf7P7:b-7ql1td) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/68f4dfaea9c3281a4661106da274aababa3553ef/store/store_block.go#L72)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

I strongly recommend to use `>=`, which is also valid for block by block case. In this way, even any bug occurred at sync layer, the data in db is still correct. Data safe is really important.

On the other hand, maybe `pop` is a better name.
</blockquote></details>

fixed
___
*[`store/store_submit.go` line 114 at r2](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdUSVis0bJLOet2QO8B:-NdYDrlt5zW-0EkPebbx:b-7ql1td) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/68f4dfaea9c3281a4661106da274aababa3553ef/store/store_submit.go#L114)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

The same with previous comment for data safe purpose.
</blockquote></details>

fixed
___
*[`sync/sync.go` line 136 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdTvN0GCxiZusZB_LIs:-NdYEdM00862iWvZRKMg:b-7ql1td) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5013ad0a6eb2ce17e3d74a8bfb3d5f9652572a4/sync/sync.go#L136)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

the `err` itself alreays contains concrete reason.
</blockquote></details>

fixed
___
*[`sync/sync.go` line 159 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdTwEGL5Eout5B86H7U:-NdYFXyH0UZe8Z1knc7c:b-7ql1td) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5013ad0a6eb2ce17e3d74a8bfb3d5f9652572a4/sync/sync.go#L159)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></summary><blockquote>

I think this could lead to considerable lags.
</blockquote></details>

fixed


<!-- Sent from Reviewable.io -->

2023-09-05 06:04 UTC, wanliqun requested changes
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3)* status: 1 of 6 files reviewed, 8 unresolved discussions (waiting on @Argeric and @boqiu)

___
*[`sync/sync.go` line 103 at r7](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdYsyMmBxYRMkhx_Wjr:-NdYsyMmBxYRMkhx_Wjs:b-x4x3l9) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/1ded102858efb2788dd457ff18236b822921285a/sync/sync.go#L103)):*
> ```Go
> 	} else {
> 		ticker.Reset(s.syncIntervalCatchUp)
> 	}
> ```

So syncer won't  be able to adapt to a low frequency even if it already catches up?  In this case,  a sync interval of 1ms would cost  ~1000`eth_blockNumber` rpc requests per second in normal stage, which could be rate limited especially if you use `Confura` as rpc provider. 



_Code quote:_
```Go
	err := s.syncOnce()

	if err != nil {
		ticker.Reset(s.syncIntervalNormal)
		return err
	} else {
		ticker.Reset(s.syncIntervalCatchUp)
	}
```


<!-- Sent from Reviewable.io -->

2023-09-05 06:21 UTC, Argeric reviewed
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3)* status: 1 of 6 files reviewed, 8 unresolved discussions (waiting on @boqiu and @wanliqun)

___
*[`sync/sync.go` line 103 at r7](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdYsyMmBxYRMkhx_Wjr:-NdZ-BmuAseHE5bIqa64:b-7ql1td) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/1ded102858efb2788dd457ff18236b822921285a/sync/sync.go#L103)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></summary><blockquote>

So syncer won't  be able to adapt to a low frequency even if it already catches up?  In this case,  a sync interval of 1ms would cost  ~1000`eth_blockNumber` rpc requests per second in normal stage, which could be rate limited especially if you use `Confura` as rpc provider.
</blockquote></details>

fixed


<!-- Sent from Reviewable.io -->

2023-09-05 06:23 UTC, boqiu requested changes
> Reviewed 5 of 5 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3)* status: all files reviewed (commit messages unreviewed), 3 unresolved discussions (waiting on @Argeric and @wanliqun)

___
*[`store/eth_data.go` line 22 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdTpzCLE4vqAjR6K9_1:-NdZ-fmPDTYmfpV6kWt4:burkoet) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5013ad0a6eb2ce17e3d74a8bfb3d5f9652572a4/store/eth_data.go#L22)):*
<details><summary><i>Previously, Argeric wrote…</i></summary><blockquote>

Yes, changed to use false isFull parameter
</blockquote></details>

Not changed yet?


<!-- Sent from Reviewable.io -->

2023-09-05 06:25 UTC, boqiu reviewed
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3)* status: all files reviewed, 3 unresolved discussions (waiting on @Argeric and @wanliqun)



<!-- Sent from Reviewable.io -->

2023-09-05 06:29 UTC, Argeric reviewed
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3)* status: 4 of 6 files reviewed, 3 unresolved discussions (waiting on @boqiu and @wanliqun)

___
*[`store/eth_data.go` line 22 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-NdTpzCLE4vqAjR6K9_1:-NdZ0tM572atazSETNrN:braungb) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5013ad0a6eb2ce17e3d74a8bfb3d5f9652572a4/store/eth_data.go#L22)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Not changed yet?
</blockquote></details>

Commited


<!-- Sent from Reviewable.io -->

2023-09-05 06:52 UTC, wanliqun approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-:-NdZ5eK-3_4-aCjuzPoo:bnfp4nl)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @boqiu)



<!-- Sent from Reviewable.io -->

2023-09-05 07:05 UTC, boqiu approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/3#-:-NdZ9DIH8evlGPknHbkk:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Argeric)



<!-- Sent from Reviewable.io -->

2023-09-05 07:18 UTC, merged