ADD: catchup mode
Conflux-Chain/neurahive-scan pull request #4
Opened 2023-09-12 09:05 UTC by Argeric

add catch up mode

2023-09-13 07:25 UTC, Tigo9527 requested changes
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4)* status: all files reviewed, 10 unresolved discussions (waiting on @Argeric, @boqiu, and @wanliqun)

___
*[`cmd/sync-context.go` line 19 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeCF2Y4-SS5b16-KQas:-NeCF2Y4-SS5b16-KQat:bwavljy) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5f754a7059d6f7a374f6a167f9fd6a5ca1db183/cmd/sync-context.go#L19)):*
> ```Go
> 
> type SdkConfig struct {
> 	Http            string
> ```

`Http` has a special meaning, consider using `Url`.
___
*[`cmd/sync-context.go` line 39 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeCGZxIAleIdyLBFTRR:-NeCGZxIAleIdyLBFTRS:b-hl8uku) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5f754a7059d6f7a374f6a167f9fd6a5ca1db183/cmd/sync-context.go#L39)):*
> ```Go
> 	}
> 
> 	cf := SdkConfig{}
> ```

`sdkCfg` as var name  ?
___
*[`config/config.yml` line 19 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeCHKEi2N8J7jstgNz7:-NeCHKEi2N8J7jstgNz8:b-ivp67b) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5f754a7059d6f7a374f6a167f9fd6a5ca1db183/config/config.yml#L19)):*
> ```YAML
>   blockWhenFlowCreated: 134253185
>   # To avoid pivot switch frequently, skip some blocks ahead of the latest block
>   skipBlocksAheadLatest: 30
> ```

It's not `skip`, but a gap or delay/behind. Consider using a more concise/precise name.
___
*[`store/eth_data.go` line 84 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeCK21S24N0lRNb96My:-NeCK21T7-hIFdOFR9OM:by0wtle) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5f754a7059d6f7a374f6a167f9fd6a5ca1db183/store/eth_data.go#L84)):*
> ```Go
> 				end = start + (end-start)/2
> 			}
> 			continue
> ```

What if other errors occur ?
___
*[`store/eth_data.go` line 100 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeCKj-10y1Y0JDzL_BB:-NeCKj-2Esh2uGkmsZFc:b-njctv9) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5f754a7059d6f7a374f6a167f9fd6a5ca1db183/store/eth_data.go#L100)):*
> ```Go
> 		ToBlock:   &bnTo,
> 		Addresses: []common.Address{common.HexToAddress(flowAddr)},
> 		Topics:    [][]common.Hash{{common.HexToHash(flowSubmitSig)}},
> ```

Computing HexToHash every time should be avoided.
___
*[`store/eth_data.go` line 105 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeCL9eO5lVimuTNkg7n:-NeCL9eO5lVimuTNkg7o:bqkh5eq) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5f754a7059d6f7a374f6a167f9fd6a5ca1db183/store/eth_data.go#L105)):*
> ```Go
> }
> 
> func MapBlockNum2Time(ctx context.Context, w3c *web3go.Client, logs *[]types.Log) (map[uint64]uint64, error) {
> ```

The functionality is more general by making the method take BlockNumbers as parameters.
At this way, need to convert the logs to BlockNumbers before calling this method.
___
*[`store/store_block.go` line 61 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeCMqOe-n4C97hAt2kH:-NeCMqOe-n4C97hAt2kI:b9z7855) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5f754a7059d6f7a374f6a167f9fd6a5ca1db183/store/store_block.go#L61)):*
> ```Go
> 		block = newBlock(endBlk)
> 	}
> ```

Data calculations should be moved outside database transactions to reduce database lock time.
___
*[`store/store_submit.go` line 92 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeCNYyO2MWTg5A_Cxgq:-NeCNYyO2MWTg5A_Cxgr:b9z7855) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5f754a7059d6f7a374f6a167f9fd6a5ca1db183/store/store_submit.go#L92)):*
> ```Go
> 		submits = append(submits, submit)
> 	}
> ```

Data calculations should be moved outside database transactions to reduce database lock time.
___
*[`sync/catchup.go` line 81 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeCOz6N7A6rcxIINBdu:-NeCOz6N7A6rcxIINBdv:b-fu45p4) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5f754a7059d6f7a374f6a167f9fd6a5ca1db183/sync/catchup.go#L81)):*
> ```Go
> 		}
> 
> 		start, end = end+1, rangeEnd
> ```

This line makes end = rangeEnd, and the `for` loop will stop after two rounds, seems incorrect.
___
*[`sync/sync.go` line 153 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeCQ2r0BW2d-jE24w8Y:-NeCQ2r0BW2d-jE24w8Z:bwyauu9) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5f754a7059d6f7a374f6a167f9fd6a5ca1db183/sync/sync.go#L153)):*
> ```Go
> 		latestStoreBlock := s.latestStoreBlock()
> 		if err := s.revertReorgData(latestStoreBlock); err != nil {
> 			return false, err
> ```

simply return false, err, without checking err != nil.  that is , this `if` is not necessary.


<!-- Sent from Reviewable.io -->

2023-09-13 10:13 UTC, Argeric reviewed
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4)* status: all files reviewed, 10 unresolved discussions (waiting on @boqiu, @Tigo9527, and @wanliqun)

___
*[`cmd/sync-context.go` line 19 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeCF2Y4-SS5b16-KQas:-NeCUYy99f5wRVmQHrPR:b-qi0f9a) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5f754a7059d6f7a374f6a167f9fd6a5ca1db183/cmd/sync-context.go#L19)):*
<details><summary><i>Previously, Tigo9527 wrote…</i></summary><blockquote>

`Http` has a special meaning, consider using `Url`.
</blockquote></details>

Yes，fixed to `Url`
___
*[`cmd/sync-context.go` line 39 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeCGZxIAleIdyLBFTRR:-NeCUvMV28QH5NhgkXj7:b-ta2l9j) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5f754a7059d6f7a374f6a167f9fd6a5ca1db183/cmd/sync-context.go#L39)):*
<details><summary><i>Previously, Tigo9527 wrote…</i></summary><blockquote>

`sdkCfg` as var name  ?
</blockquote></details>

Yes， fixed to `sdkCfg`
___
*[`config/config.yml` line 19 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeCHKEi2N8J7jstgNz7:-NeCWgGi-IibPRtNY6hE:b-hpjjcs) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5f754a7059d6f7a374f6a167f9fd6a5ca1db183/config/config.yml#L19)):*
<details><summary><i>Previously, Tigo9527 wrote…</i></summary><blockquote>

It's not `skip`, but a gap or delay/behind. Consider using a more concise/precise name.
</blockquote></details>

Yes, fixed to `DelayBlocksAgainstLatest`
___
*[`store/eth_data.go` line 84 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeCK21S24N0lRNb96My:-NeCae096j3ek2RASSWz:bi0o96e) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5f754a7059d6f7a374f6a167f9fd6a5ca1db183/store/eth_data.go#L84)):*
<details><summary><i>Previously, Tigo9527 wrote…</i></summary><blockquote>

What if other errors occur ?
</blockquote></details>

A time-out error may occur when catchup-mode syncing against finalized state，and it has not been encountered so far.
___
*[`store/eth_data.go` line 100 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeCKj-10y1Y0JDzL_BB:-NeCeI933wIyJakZ2Z2T:b-xsv2vg) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5f754a7059d6f7a374f6a167f9fd6a5ca1db183/store/eth_data.go#L100)):*
<details><summary><i>Previously, Tigo9527 wrote…</i></summary><blockquote>

Computing HexToHash every time should be avoided.
</blockquote></details>


Fixed. Put the conversion operation in the catchup syncer's initialization.
___
*[`store/eth_data.go` line 105 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeCL9eO5lVimuTNkg7n:-NeCfJ_WAhoyZnqYgLPe:b5wkfqs) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5f754a7059d6f7a374f6a167f9fd6a5ca1db183/store/eth_data.go#L105)):*
<details><summary><i>Previously, Tigo9527 wrote…</i></summary><blockquote>

The functionality is more general by making the method take BlockNumbers as parameters.
At this way, need to convert the logs to BlockNumbers before calling this method.
</blockquote></details>

Fixed to take BlockNumbers as parameters.
___
*[`store/store_block.go` line 61 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeCMqOe-n4C97hAt2kH:-NeClxD62arQs8uXDOIY:bt2vr1b) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5f754a7059d6f7a374f6a167f9fd6a5ca1db183/store/store_block.go#L61)):*
<details><summary><i>Previously, Tigo9527 wrote…</i></summary><blockquote>

Data calculations should be moved outside database transactions to reduce database lock time.
</blockquote></details>

Fixed.
___
*[`store/store_submit.go` line 92 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeCNYyO2MWTg5A_Cxgq:-NeCuCaRALx8OAlTyMP3:b-886gsx) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5f754a7059d6f7a374f6a167f9fd6a5ca1db183/store/store_submit.go#L92)):*
<details><summary><i>Previously, Tigo9527 wrote…</i></summary><blockquote>

Data calculations should be moved outside database transactions to reduce database lock time.
</blockquote></details>

Fixed
___
*[`sync/catchup.go` line 81 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeCOz6N7A6rcxIINBdu:-NeCyoY21vibkntJBgdt:bcm0unv) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5f754a7059d6f7a374f6a167f9fd6a5ca1db183/sync/catchup.go#L81)):*
<details><summary><i>Previously, Tigo9527 wrote…</i></summary><blockquote>

This line makes end = rangeEnd, and the `for` loop will stop after two rounds, seems incorrect.
</blockquote></details>

The end's value will be adjusted in the `tryflowSubmission` method if the query result contains more than 10000 logs.
___
*[`sync/sync.go` line 153 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeCQ2r0BW2d-jE24w8Y:-NeD06g_99Fm_B45pdGD:b-o18ka9) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5f754a7059d6f7a374f6a167f9fd6a5ca1db183/sync/sync.go#L153)):*
<details><summary><i>Previously, Tigo9527 wrote…</i></summary><blockquote>

simply return false, err, without checking err != nil.  that is , this `if` is not necessary.
</blockquote></details>

OK, fixed.


<!-- Sent from Reviewable.io -->

2023-09-14 06:25 UTC, wanliqun requested changes
> Reviewed 1 of 12 files at r1, 3 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4)* status: 7 of 12 files reviewed, 32 unresolved discussions (waiting on @Argeric, @boqiu, and @Tigo9527)

___
*[`main.go` line 9 at r2](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeGOLNm3oHbqETE7DmJ:-NeGOLNm3oHbqETE7DmK:bwwndsq) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/378c12054a8e9a67baaaab68c8249a089c84d4ed/main.go#L9)):*
> ```Go
> 
> func main() {
> 	config.MustInit("neurahive-scan")
> ```

We use `_` as separator for enviorment variables in viper, so use `neurahive_scan` to conform to the same rule or you can just use `neurahive` for short.
___
*[`cmd/root.go` line 27 at r2](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeGP_to-ns5TRE98wU3:-NeGP_to-ns5TRE98wU4:b-sn491m) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/378c12054a8e9a67baaaab68c8249a089c84d4ed/cmd/root.go#L27)):*
> ```Go
> func initConfig() {
> 	config.MustInit("")
> }*/
> ```

remove these unused codes if they are not necessary any more.



_Code quote:_
```Go
/*func init() {
	cobra.OnInitialize(initConfig)
}

func initConfig() {
	config.MustInit("")
}*/
```
___
*[`cmd/sync.go` line 18 at r2](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeGPtNbCIgSaHA16bt_:-NeGPtNbCIgSaHA16bta:b-5ixzoj) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/378c12054a8e9a67baaaab68c8249a089c84d4ed/cmd/sync.go#L18)):*
> ```Go
> 	syncCmd = &cobra.Command{
> 		Use:   "sync",
> 		Short: "Start sync sync, including block/tx/submitLog",
> ```

typo  two `sync`?
___
*[`cmd/sync-context.go` line 0 at r2](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeGRiG_2-t5EeNaJW5G:-NeGRiG_2-t5EeNaJW5H:ba17fkq) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/378c12054a8e9a67baaaab68c8249a089c84d4ed/cmd/sync-context.go#L0)):*
use `_` in filename in accordance with go naming convention
___
*[`cmd/sync-context.go` line 36 at r2](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeGVFFx0Ep-ejUEpRpT:-NeGVFFx0Ep-ejUEpRpU:b79geeu) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/378c12054a8e9a67baaaab68c8249a089c84d4ed/cmd/sync-context.go#L36)):*
> ```Go
> 	db := cfg.MustOpenOrCreate()
> 	if err := db.AutoMigrate(migrationModels...); err != nil {
> 		logrus.Fatalln("migrate database fail:", err.Error())
> ```

use `logrus.WithError(err).Fatalln("...")` instead?
___
*[`cmd/sync-context.go` line 42 at r2](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeGWMZC59ksdKbAveTl:-NeGWMZC59ksdKbAveTm:b-qt7vwl) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/378c12054a8e9a67baaaab68c8249a089c84d4ed/cmd/sync-context.go#L42)):*
> ```Go
> 	viper.MustUnmarshalKey("eth", &sdkCfg)
> 	opt := web3go.ClientOption{}
> 	opt.WithRetry(sdkCfg.Retry, sdkCfg.RetryInterval).WithTimout(sdkCfg.RequestTimeout).WithMaxConnectionPerHost(sdkCfg.MaxConnsPerHost)
> ```

use newline for readibility
___
*[`cmd/sync-context.go` line 49 at r2](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeGWt4P71Le7p0IlLJ0:-NeGWt4P71Le7p0IlLJ1:bs7yw8l) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/378c12054a8e9a67baaaab68c8249a089c84d4ed/cmd/sync-context.go#L49)):*
> ```Go
> 	ctx.Eth = eth
> 
> 	return ctx
> ```

maybe you can just return for short:
```
return SyncContext {
  DB: store.MustNewStore(db),
  Eth: eth
}
```



_Code quote:_
```Go
	var ctx SyncContext
	ctx.DB = store.MustNewStore(db)
	ctx.Eth = eth

	return ctx
```
___
*[`store/eth_data.go` line 84 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeCK21S24N0lRNb96My:-NeGbxTkASZYbgHxr3e9:b-yfuvz6) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5f754a7059d6f7a374f6a167f9fd6a5ca1db183/store/eth_data.go#L84)):*
<details><summary><i>Previously, Argeric wrote…</i></summary><blockquote>

A time-out error may occur when catchup-mode syncing against finalized state，and it has not been encountered so far.
</blockquote></details>

Shall we continue the for loop no matter of what kind of error it is?
___
*[`store/eth_data.go` line 74 at r2](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeGdqr89-mXEDjR2roi:-NeGdqr89-mXEDjR2roj:bl0r94a) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/378c12054a8e9a67baaaab68c8249a089c84d4ed/store/eth_data.go#L74)):*
> ```Go
> }
> 
> func TryFlowSubmits(w3c *web3go.Client, bnFrom, bnTo uint64, flowAddr common.Address, flowSubmitSig common.Hash) (*[]types.Log, uint64, uint64) {
> ```

`TryFlowSubmits` doesn't seem to be a good function name. BTW, can't we just put these kind of logics into `sync` package?
___
*[`store/eth_data.go` line 105 at r2](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeGfJeLE4Ope8AldgE2:-NeGfJeMDtymod2qFYn5:bdlyfju) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/378c12054a8e9a67baaaab68c8249a089c84d4ed/store/eth_data.go#L105)):*
> ```Go
> }
> 
> func MapBlockNum2Time(ctx context.Context, w3c *web3go.Client, blkNums *[]types.BlockNumber) (map[uint64]uint64, error) {
> ```

Use `blkNums []types.BlockNumber` is enough. It is not recommended to use pointers to slices, as slices are already small headers pointing to a backing array. Using pointers to slices can introduce unnecessary complexity and confusion.
___
*[`store/eth_data.go` line 111 at r2](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeGjm8i-Nt06Z_HWBAj:-NeGjm8i-Nt06Z_HWBAk:b-1rcff6) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/378c12054a8e9a67baaaab68c8249a089c84d4ed/store/eth_data.go#L111)):*
> ```Go
> 
> 	batch := make([]rpc.BatchElem, 0)
> 	for _, blkNum := range *blkNums {
> ```

dedupe before batch? 
___
*[`store/store.go` line 33 at r2](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeGgywy63KYvVbaMF54:-NeGgywy63KYvVbaMF55:b-54hk5l) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/378c12054a8e9a67baaaab68c8249a089c84d4ed/store/store.go#L33)):*
> ```Go
> 		Address              string
> 		SubmitEventSignature string
> 	}
> ```

Why `store` needs a `flow` config if they are role separated?



_Code quote:_
```Go
	var flow struct {
		Address              string
		SubmitEventSignature string
	}
```
___
*[`store/store.go` line 46 at r2](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeHI59z5bykWtfsc-Da:-NeHHwJF5ZF_ra1R1fzT:b-jon2le) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/378c12054a8e9a67baaaab68c8249a089c84d4ed/store/store.go#L46)):*
> ```Go
> }
> 
> func (ms *MysqlStore) PushCatchup(logs *[]types.Log, blockNum2TimeMap map[uint64]uint64, rangeEndBlock *types.Block) error {
> ```

It seems a littile bit wierd if we need to have a separate logic to store the catchup data. Can we adapt them at the `sync` pkg?
___
*[`store/store_block.go` line 27 at r2](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeHM7d4AEkHVz6DPV3H:-NeHM7d4AEkHVz6DPV3I:b-7ropln) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/378c12054a8e9a67baaaab68c8249a089c84d4ed/store/store_block.go#L27)):*
> ```Go
> }
> 
> func NewBlockOnCatchup(logs *[]types.Log, blockNum2TimeMap map[uint64]uint64, endBlk *types.Block) *Block {
> ```

ditto
___
*[`store/store_submit.go` line 87 at r2](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeHM9rJ9rW-Tt3-s1Gq:-NeHM9rJ9rW-Tt3-s1Gr:b-7ropln) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/378c12054a8e9a67baaaab68c8249a089c84d4ed/store/store_submit.go#L87)):*
> ```Go
> }
> 
> func NewSubmitsOnCatchup(logs *[]types.Log, blockNum2TimeMap map[uint64]uint64, as *addressStore) ([]*Submit, error) {
> ```

ditto
___
*[`sync/catchup.go` line 62 at r2](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeGp9gQ69FgUu2oRcVI:-NeGp9gQ69FgUu2oRcVJ:b-7ropln) ([raw file](https://gi [...]

2023-09-14 06:40 UTC, Tigo9527 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-:-NeHPpcKBnALrJTty5aK:bnfp4nl)* status: all files reviewed, 23 unresolved discussions (waiting on @Argeric, @boqiu, and @wanliqun)

___
*[`store/eth_data.go` line 84 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeCK21S24N0lRNb96My:-NeHL3Vg9rhLcUzDDi8h:bkjqame) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5f754a7059d6f7a374f6a167f9fd6a5ca1db183/store/eth_data.go#L84)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></summary><blockquote>

Shall we continue the for loop no matter of what kind of error it is?
</blockquote></details>

If other errors occur, an infinite loop will occur.


<!-- Sent from Reviewable.io -->

2023-09-14 10:12 UTC, Argeric reviewed
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4)* status: 3 of 13 files reviewed, 23 unresolved discussions (waiting on @boqiu, @Tigo9527, and @wanliqun)

___
*[`main.go` line 9 at r2](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeGOLNm3oHbqETE7DmJ:-NeHNwpT4injU9ubCYVB:b-l8j71d) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/378c12054a8e9a67baaaab68c8249a089c84d4ed/main.go#L9)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></summary><blockquote>

We use `_` as separator for enviorment variables in viper, so use `neurahive_scan` to conform to the same rule or you can just use `neurahive` for short.
</blockquote></details>

Ok, fixed to `neurahive`
___
*[`cmd/root.go` line 27 at r2](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeGP_to-ns5TRE98wU3:-NeHODgO4C_NGC08765w:ba3dfob) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/378c12054a8e9a67baaaab68c8249a089c84d4ed/cmd/root.go#L27)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></summary><blockquote>

remove these unused codes if they are not necessary any more.
</blockquote></details>

Removed
___
*[`cmd/sync.go` line 18 at r2](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeGPtNbCIgSaHA16bt_:-NeHOOZc4KL1_7afWqsj:b-886gsx) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/378c12054a8e9a67baaaab68c8249a089c84d4ed/cmd/sync.go#L18)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></summary><blockquote>

typo  two `sync`?
</blockquote></details>

Fixed
___
*[`store/eth_data.go` line 84 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeCK21S24N0lRNb96My:-NeHwMRNAft_rg0PZ68g:b25s20p) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5f754a7059d6f7a374f6a167f9fd6a5ca1db183/store/eth_data.go#L84)):*
<details><summary><i>Previously, Tigo9527 wrote…</i></summary><blockquote>

If other errors occur, an infinite loop will occur.
</blockquote></details>

The error will be throwed to outer function `sync`, and  go routine will sleep 1 sec.
___
*[`store/eth_data.go` line 74 at r2](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeGdqr89-mXEDjR2roi:-NeHQ_XqEjwaR-d3vfIf:bi32uw6) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/378c12054a8e9a67baaaab68c8249a089c84d4ed/store/eth_data.go#L74)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></summary><blockquote>

`TryFlowSubmits` doesn't seem to be a good function name. BTW, can't we just put these kind of logics into `sync` package?
</blockquote></details>

Yes, fixed to use func name `queryFlowSubmits` and this kind of logic has been put into `sync` package. 
___
*[`store/eth_data.go` line 105 at r2](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeGfJeLE4Ope8AldgE2:-NeHUH3d79fmXhSDYJAw:b-q2nfwk) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/378c12054a8e9a67baaaab68c8249a089c84d4ed/store/eth_data.go#L105)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></summary><blockquote>

Use `blkNums []types.BlockNumber` is enough. It is not recommended to use pointers to slices, as slices are already small headers pointing to a backing array. Using pointers to slices can introduce unnecessary complexity and confusion.
</blockquote></details>

Fixed, thanks for reminding.
___
*[`store/eth_data.go` line 111 at r2](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeGjm8i-Nt06Z_HWBAj:-NeH_jL8CI_8usYx5Hme:b-nr9qtm) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/378c12054a8e9a67baaaab68c8249a089c84d4ed/store/eth_data.go#L111)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></summary><blockquote>

dedupe before batch?
</blockquote></details>

Deduped.
___
*[`store/store.go` line 33 at r2](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeGgywy63KYvVbaMF54:-NeHeffCClJNnS3gsWQZ:bt2vr1b) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/378c12054a8e9a67baaaab68c8249a089c84d4ed/store/store.go#L33)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></summary><blockquote>

Why `store` needs a `flow` config if they are role separated?
</blockquote></details>

Fixed.
___
*[`store/store.go` line 46 at r2](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeHI59z5bykWtfsc-Da:-NeHmPhCDsMll5Sw-7gN:b-cevoy6) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/378c12054a8e9a67baaaab68c8249a089c84d4ed/store/store.go#L46)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></summary><blockquote>

It seems a littile bit wierd if we need to have a separate logic to store the catchup data. Can we adapt them at the `sync` pkg?
</blockquote></details>

Fixe to use unified logic for storing， and put the logic of  assembling data into `sync` pkg
___
*[`store/store_block.go` line 27 at r2](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeHM7d4AEkHVz6DPV3H:-NeHmsf09mSMRV1yzbXS:bt2vr1b) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/378c12054a8e9a67baaaab68c8249a089c84d4ed/store/store_block.go#L27)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Fixed.
___
*[`store/store_submit.go` line 87 at r2](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeHM9rJ9rW-Tt3-s1Gq:-NeHnKhp7qcDL_VbXJ-9:bt2vr1b) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/378c12054a8e9a67baaaab68c8249a089c84d4ed/store/store_submit.go#L87)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Fixed.
___
*[`sync/catchup.go` line 62 at r2](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeGp9gQ69FgUu2oRcVI:-NeHnTQs5e85wM4-JORA:bt2vr1b) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/378c12054a8e9a67baaaab68c8249a089c84d4ed/sync/catchup.go#L62)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Fixed.
___
*[`sync/catchup.go` line 92 at r2](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeHCjY_8vQBLHoNrXyI:-NeHpKUiEBfUGBW_fz6u:bd205ys) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/378c12054a8e9a67baaaab68c8249a089c84d4ed/sync/catchup.go#L92)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></summary><blockquote>

`end = start + s.conf.BatchBlocksOnCatchup - 1`? And I believe you can combie the above similar block range segment logic with this one.
</blockquote></details>

Oh, fixed. 
___
*[`sync/catchup.go` line 101 at r2](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeGnVW--za0H-s4C7Ix:-NeHpnN4BL9lzsrI_otI:ba1bclt) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/378c12054a8e9a67baaaab68c8249a089c84d4ed/sync/catchup.go#L101)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></summary><blockquote>

what is the point to use `try`variable here?
</blockquote></details>

OK, fixed to use `ok`?  The variable `try` is used in outer loop already.
___
*[`sync/catchup.go` line 108 at r2](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeGnA0876BfFlicoLbm:-NeHscWq7aSTjOCca0KH:bt2vr1b) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/378c12054a8e9a67baaaab68c8249a089c84d4ed/sync/catchup.go#L108)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></summary><blockquote>

always handle error at first.
</blockquote></details>

Fixed.
___
*[`sync/catchup.go` line 109 at r2](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeGn12mDLpiy_7DsAbH:-NeHumMf1Il6WWQr1ve6:bt2vr1b) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/378c12054a8e9a67baaaab68c8249a089c84d4ed/sync/catchup.go#L109)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></su [...]

2023-09-15 03:47 UTC, wanliqun requested changes
> Reviewed 4 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4)* status: 7 of 13 files reviewed, 13 unresolved discussions (waiting on @Argeric, @boqiu, and @Tigo9527)

___
*[`store/eth_data.go` line 84 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeCK21S24N0lRNb96My:-NeLaUM5E0Sz3WPNP44o:b-uzv6ad) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5f754a7059d6f7a374f6a167f9fd6a5ca1db183/store/eth_data.go#L84)):*
<details><summary><i>Previously, Argeric wrote…</i></summary><blockquote>

The error will be throwed to outer function `sync`, and  go routine will sleep 1 sec.
</blockquote></details>

Also remember to log the error so that an alert can be triggered.
___
*[`store/eth_data.go` line 74 at r2](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeGdqr89-mXEDjR2roi:-NeLaikL8qtjgsZ4aRR_:bcklw7v) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/378c12054a8e9a67baaaab68c8249a089c84d4ed/store/eth_data.go#L74)):*
<details><summary><i>Previously, Argeric wrote…</i></summary><blockquote>

Yes, fixed to use func name `queryFlowSubmits` and this kind of logic has been put into `sync` package.
</blockquote></details>

 The function is trying to query flow submits event logs between a block range of (bnFrom, bnTo), but it may not get all the data for the whole range. In that case,I would recommend a function name that reflects this behavior, such as `queryFlowSubmitsPartial` or `queryFlowSubmitsBestEffort`. These names indicate that the function may not return the complete data for the requested range, but only the available or feasible data.

Also add more comments to explain how the behavior for this function eg.,
```go
// queryFlowSubmitsBestEffort queries flow submits from the contract event logs between a block range of (bnFrom, bnTo).
// It returns the logs, the actual start and end block numbers of the queried range, and an error if any.
// It may not return all the data for the whole range, but only the available or feasible data.
// It uses a binary search algorithm to find the optimal range that maximizes the number of logs returned.
```
___
*[`store/eth_data.go` line 106 at r3](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeLeiwZAh3m9ceHXK4A:-NeLeiwZAh3m9ceHXK4B:b-xohyy0) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/4df7a6a578b35f62785fba4fb7352b6ab89be73b/store/eth_data.go#L106)):*
> ```Go
> 	}
> 
> 	err := w3c.Eth.BatchCallContext(ctx, batch)
> ```

Ideally, this `eth_getBlockNumber` batch size wouldn't be too big. If we didn't split the batch,  still better to add some TODO or comments here.
___
*[`store/store_block.go` line 27 at r2](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeHM7d4AEkHVz6DPV3H:-NeLuxLjD-CIank7wXho:b-lx040w) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/378c12054a8e9a67baaaab68c8249a089c84d4ed/store/store_block.go#L27)):*
<details><summary><i>Previously, Argeric wrote…</i></summary><blockquote>

Fixed.
</blockquote></details>

Maybe we can put this adapt logic for catchup into the `sync` pkg. 
`store` pkg shouldn't care about `catchup` stuff.
___
*[`store/store_submit.go` line 87 at r2](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeHM9rJ9rW-Tt3-s1Gq:-NeLvFn8Bcoq5c3gTTr5:bfscdh) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/378c12054a8e9a67baaaab68c8249a089c84d4ed/store/store_submit.go#L87)):*
<details><summary><i>Previously, Argeric wrote…</i></summary><blockquote>

Fixed.
</blockquote></details>

Maybe we can put this adapt logic for catchup into the `sync` pkg. 
___
*[`sync/catchup.go` line 62 at r2](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeGp9gQ69FgUu2oRcVI:-NeLiBZ36h58dPrh3dWE:bz4rtcf) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/378c12054a8e9a67baaaab68c8249a089c84d4ed/sync/catchup.go#L62)):*
<details><summary><i>Previously, Argeric wrote…</i></summary><blockquote>

Fixed.
</blockquote></details>

`*[]types.Log` pointer to slice still be used?
___
*[`sync/catchup.go` line 92 at r2](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeHCjY_8vQBLHoNrXyI:-NeLiMoX6UjhEz0Tiztt:b-jmrtsc) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/378c12054a8e9a67baaaab68c8249a089c84d4ed/sync/catchup.go#L92)):*
<details><summary><i>Previously, Argeric wrote…</i></summary><blockquote>

Oh, fixed.
</blockquote></details>

I've noticed you've actually written this kind of logic twice (line 58 and line 103), try to merge them as one:
```
start, end := rangeStart, rangeEnd
	if s.conf.BatchBlocksOnCatchup > 0 {
		end = rangeStart + s.conf.BatchBlocksOnCatchup - 1
		if end > rangeEnd {
			end = rangeEnd
		}
	}
```
___
*[`sync/catchup.go` line 115 at r3](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeLjXRw1l49kX4bIeOs:-NeLjXRw1l49kX4bIeOt:b-8b06ji) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/4df7a6a578b35f62785fba4fb7352b6ab89be73b/sync/catchup.go#L115)):*
> ```Go
> }
> 
> func (s *CatchupSyncer) queryFlowSubmits(w3c *web3go.Client, bnFrom, bnTo uint64, flowAddr common.Address, flowSubmitSig common.Hash) (*[]types.Log, uint64, uint64, error) {
> ```

See comments mentioned before:
1. *[]types.Log
2. function name
3. comments
___
*[`sync/catchup.go` line 128 at r3](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeLjzCp5ezuGuytLBuj:-NeLjzCp5ezuGuytLBuk:b6d5hti) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/4df7a6a578b35f62785fba4fb7352b6ab89be73b/sync/catchup.go#L128)):*
> ```Go
> 			return nil, 0, 0, err
> 		}
> 		logs = &result
> ```

I blieve you can direcly return if err = nil here.
___
*[`sync/catchup.go` line 170 at r3](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeLk_AO7gPcNtlqpoa5:-NeLk_AO7gPcNtlqpoa6:b-5ax6gh) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/4df7a6a578b35f62785fba4fb7352b6ab89be73b/sync/catchup.go#L170)):*
> ```Go
> 
> 	if s.currentBlock < s.finalizedBlock {
> 		return true, nil
> ```

If you function `updateBlockRange` is to update block numbers, I don't think it's a good idea to compare `currentblock < finalizedBlock` here. Just return error is enough.



_Code quote:_
```Go
	if s.currentBlock < s.finalizedBlock {
		return true, nil
```
___
*[`sync/sync.go` line 204 at r3](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeLtOHl4guRUV1LdWNI:-NeLtOHl4guRUV1LdWNJ:b-b57f82) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/4df7a6a578b35f62785fba4fb7352b6ab89be73b/sync/sync.go#L204)):*
> ```Go
> 
> func (s *Syncer) checkReorgData() error {
> 	for {
> ```

Ideally, one by one block to check and prune reorg data is fine though this could be improved with binary search probing. Suggest to add some comments or TODO.
___
*[`cmd/sync-context.go` line 42 at r2](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeGWMZC59ksdKbAveTl:-NeL__obDZ7rM8whPCCM:bwjf4bt) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/378c12054a8e9a67baaaab68c8249a089c84d4ed/cmd/sync-context.go#L42)):*
<details><summary><i>Previously, Argeric wrote…</i></summary><blockquote>

Fixed
</blockquote></details>

You can use chain operations like:
```go
opt.WithRetry(sdkCfg.Retry, sdkCfg.RetryInterval).
    WithTimout(sdkCfg.RequestTimeout).
    WithMaxConnectionPerHost(sdkCfg.MaxConnsPerHost)
```


<!-- Sent from Reviewable.io -->

2023-09-15 08:21 UTC, Argeric reviewed
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4)* status: 7 of 13 files reviewed, 13 unresolved discussions (waiting on @boqiu, @Tigo9527, and @wanliqun)

___
*[`store/eth_data.go` line 84 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeCK21S24N0lRNb96My:-NeM-QlqEJTRNS_BZO3D:b-886gsx) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/a5f754a7059d6f7a374f6a167f9fd6a5ca1db183/store/eth_data.go#L84)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></summary><blockquote>

Also remember to log the error so that an alert can be triggered.
</blockquote></details>

Fixed
___
*[`store/eth_data.go` line 74 at r2](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeGdqr89-mXEDjR2roi:-NeM05PKDPTD-nC99sgm:b-5y1hw1) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/378c12054a8e9a67baaaab68c8249a089c84d4ed/store/eth_data.go#L74)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></summary><blockquote>

The function is trying to query flow submits event logs between a block range of (bnFrom, bnTo), but it may not get all the data for the whole range. In that case,I would recommend a function name that reflects this behavior, such as `queryFlowSubmitsPartial` or `queryFlowSubmitsBestEffort`. These names indicate that the function may not return the complete data for the requested range, but only the available or feasible data.

Also add more comments to explain how the behavior for this function eg.,
```go
// queryFlowSubmitsBestEffort queries flow submits from the contract event logs between a block range of (bnFrom, bnTo).
// It returns the logs, the actual start and end block numbers of the queried range, and an error if any.
// It may not return all the data for the whole range, but only the available or feasible data.
// It uses a binary search algorithm to find the optimal range that maximizes the number of logs returned.
```
</blockquote></details>

Good idea, thanks!
___
*[`store/eth_data.go` line 106 at r3](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeLeiwZAh3m9ceHXK4A:-NeMUQYe9kZBehRtJhjQ:b2lhhwz) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/4df7a6a578b35f62785fba4fb7352b6ab89be73b/store/eth_data.go#L106)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></summary><blockquote>

Ideally, this `eth_getBlockNumber` batch size wouldn't be too big. If we didn't split the batch,  still better to add some TODO or comments here.
</blockquote></details>

Fixed, param `batchSize` is added.
___
*[`store/store_block.go` line 27 at r2](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeHM7d4AEkHVz6DPV3H:-NeMZK0X1TsMr9iAhyIt:b-fmywpt) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/378c12054a8e9a67baaaab68c8249a089c84d4ed/store/store_block.go#L27)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></summary><blockquote>

Maybe we can put this adapt logic for catchup into the `sync` pkg. 
`store` pkg shouldn't care about `catchup` stuff.
</blockquote></details>

Good idea, removed to `sync` pkg. 
___
*[`store/store_submit.go` line 87 at r2](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeHM9rJ9rW-Tt3-s1Gq:-NeMZVcwClkvD1cEM97r:b-fmywpt) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/378c12054a8e9a67baaaab68c8249a089c84d4ed/store/store_submit.go#L87)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></summary><blockquote>

Maybe we can put this adapt logic for catchup into the `sync` pkg.
</blockquote></details>

Good idea, removed to `sync` pkg. 
___
*[`sync/catchup.go` line 62 at r2](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeGp9gQ69FgUu2oRcVI:-NeMZti09eMLRBsoeZlV:bt2vr1b) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/378c12054a8e9a67baaaab68c8249a089c84d4ed/sync/catchup.go#L62)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></summary><blockquote>

`*[]types.Log` pointer to slice still be used?
</blockquote></details>

Fixed.
___
*[`sync/catchup.go` line 92 at r2](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeHCjY_8vQBLHoNrXyI:-NeM_0DD32YutKELtnXK:b9a4u7l) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/378c12054a8e9a67baaaab68c8249a089c84d4ed/sync/catchup.go#L92)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></summary><blockquote>

I've noticed you've actually written this kind of logic twice (line 58 and line 103), try to merge them as one:
```
start, end := rangeStart, rangeEnd
	if s.conf.BatchBlocksOnCatchup > 0 {
		end = rangeStart + s.conf.BatchBlocksOnCatchup - 1
		if end > rangeEnd {
			end = rangeEnd
		}
	}
```
</blockquote></details>

The logic has been extracted into func `nextSyncRange`.
___
*[`sync/catchup.go` line 115 at r3](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeLjXRw1l49kX4bIeOs:-NeMd0Gg5kNJ7RqaRtHl:b-owi4k2) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/4df7a6a578b35f62785fba4fb7352b6ab89be73b/sync/catchup.go#L115)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></summary><blockquote>

See comments mentioned before:
1. *[]types.Log
2. function name
3. comments
</blockquote></details>

OK, fixed all.
___
*[`sync/catchup.go` line 128 at r3](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeLjzCp5ezuGuytLBuj:-NeMg2whCzwSBiQX33em:bt2vr1b) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/4df7a6a578b35f62785fba4fb7352b6ab89be73b/sync/catchup.go#L128)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></summary><blockquote>

I blieve you can direcly return if err = nil here.
</blockquote></details>

Fixed.
___
*[`sync/catchup.go` line 170 at r3](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeLk_AO7gPcNtlqpoa5:-NeMvTxE158Mi3vnYH26:b-886gsx) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/4df7a6a578b35f62785fba4fb7352b6ab89be73b/sync/catchup.go#L170)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></summary><blockquote>

If you function `updateBlockRange` is to update block numbers, I don't think it's a good idea to compare `currentblock < finalizedBlock` here. Just return error is enough.
</blockquote></details>

Fixed
___
*[`sync/sync.go` line 204 at r3](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeLtOHl4guRUV1LdWNI:-NeMhZ4p1-J_liSVvJyr:b-8b11j9) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/4df7a6a578b35f62785fba4fb7352b6ab89be73b/sync/sync.go#L204)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></summary><blockquote>

Ideally, one by one block to check and prune reorg data is fine though this could be improved with binary search probing. Suggest to add some comments or TODO.
</blockquote></details>

Added
___
*[`cmd/sync-context.go` line 42 at r2](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeGWMZC59ksdKbAveTl:-NeM-Mxe9O_6dcgcFlHr:b-886gsx) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/378c12054a8e9a67baaaab68c8249a089c84d4ed/cmd/sync-context.go#L42)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></summary><blockquote>

You can use chain operations like:
```go
opt.WithRetry(sdkCfg.Retry, sdkCfg.RetryInterval).
    WithTimout(sdkCfg.RequestTimeout).
    WithMaxConnectionPerHost(sdkCfg.MaxConnsPerHost)
```
</blockquote></details>

Fixed


<!-- Sent from Reviewable.io -->

2023-09-15 08:54 UTC, wanliqun requested changes
> Reviewed 6 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4)* status: 10 of 13 files reviewed, 2 unresolved discussions (waiting on @Argeric, @boqiu, and @Tigo9527)

___
*[`config/config.yml` line 23 at r4](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeN0TAR9s0Gdd1Mui8-:-NeN0TAR9s0Gdd1Mui80:b-uudgux) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/3e3132b2c13a8fa4c477275caa7b5553bedc5820/config/config.yml#L23)):*
> ```YAML
>   batchBlocksOnCatchup: 0
>   # The number of blocks to query at a batch all
>   BatchBlocksOnBatchCall: 0
> ```

Better to use a default value for`BatchBlocksOnBatchCall` here, otherwise `0` will overide your default value.
Besides, config items with a stable default value can be commented out too.



_Code quote:_
```YAML
  # The number of blocks to query at a time during catchup, 0 means no limit
  batchBlocksOnCatchup: 0
  # The number of blocks to query at a batch all
  BatchBlocksOnBatchCall: 0
```
___
*[`sync/catchup.go` line 159 at r4](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeN-aIC2S0bOmNPwR6w:-NeN-aIC2S0bOmNPwR6x:buw1aog) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/3e3132b2c13a8fa4c477275caa7b5553bedc5820/sync/catchup.go#L159)):*
> ```Go
> 		}
> 
> 		return true
> ```

how about just returning `s.currentBlock < s.finalizedBlock`?



_Code quote:_
```Go
		if s.currentBlock > s.finalizedBlock {
			return false
		}

		return true
```


<!-- Sent from Reviewable.io -->

2023-09-15 09:09 UTC, Argeric reviewed
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4)* status: 10 of 13 files reviewed, 2 unresolved discussions (waiting on @boqiu, @Tigo9527, and @wanliqun)

___
*[`config/config.yml` line 23 at r4](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeN0TAR9s0Gdd1Mui8-:-NeN3wpn5mzs3lZCQswT:b4pu7pp) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/3e3132b2c13a8fa4c477275caa7b5553bedc5820/config/config.yml#L23)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></summary><blockquote>

Better to use a default value for`BatchBlocksOnBatchCall` here, otherwise `0` will overide your default value.
Besides, config items with a stable default value can be commented out too.
</blockquote></details>

Fixed, using default value by commented out config item.
___
*[`sync/catchup.go` line 159 at r4](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-NeN-aIC2S0bOmNPwR6w:-NeN560d7PgDl8DuogNp:b2dd7s3) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/3e3132b2c13a8fa4c477275caa7b5553bedc5820/sync/catchup.go#L159)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></summary><blockquote>

how about just returning `s.currentBlock < s.finalizedBlock`?
</blockquote></details>

Good idea, fixed.


<!-- Sent from Reviewable.io -->

2023-09-15 09:12 UTC, wanliqun approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 10 files at r3, 1 of 7 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/4#-:-NeN6FrL5QSWnNa9fAeZ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @boqiu)



<!-- Sent from Reviewable.io -->

2023-09-15 09:14 UTC, merged